### PR TITLE
Implement rom size as input parameter

### PR DESCRIPTION
**Pull request by ADiea**
- Implement rom size as input param: this controls how much flash is used for storing fs
- Replace errno to fix windows compile err: windows complains using errno, says it's a function
- Modify fopen param from r to rb; file read failed on my system by using "r" without the binary open mode

### CODE REVIEW

**Comment by DonKinzer** [comment]
My first solution was to change 'errno' to 'errNum'.  A simpler solution is to #undef errno.  I added the following lines at about line 44 of spiffs.h:

#if defined(WIN32)
  #undef errno
#endif

**Comment by DimmKirr** [comment]
@DonKinzer that solution didn't seem to work completely. It was building but files were still partially corrupted

**Comment by alonewolfx2** [comment]
@ADiea this patch doesn't work on Windows. Also files corrupted. @xlfe I maked a global patch for file sizes, selectable folder, default rom sizes. It's working correctly on Linux, Windows and osx. Also it's working with bigger files. I will make a PR.

**Comment by ADiea** [comment]
@alonewolfx2 I noticed that you too use default size 192K Is it possible to use smaller rom size without file corruption? 

I did not yet have time to fully test this so if your patch is better please make pr

**Comment by alonewolfx2** [comment]
@ADiea yes it is possible. 16k or smaller default size can be possible.@kireevco and i are using my code more than a month.

**Comment by DimmKirr** [comment]
by the way, binaries are available here https://bintray.com/kireevco/generic/spiffy/view

**Comment by ADiea** [comment]
@alonewolfx2 @kireevco thanks guys. I will look over your code for relevant changes and if it's ok with you will integrate with my code. cheers!

**Comment by ADiea** [comment]
@alonewolfx2 looking at https://github.com/alonewolfx2/spiffy the only relevant change I see is 

```
cfg.log_block_size = SPI_FLASH_SEC_SIZE*2;
```

The rest seems related to basedir and rom_length parameters Are there other changes necessary to make this work ?

Thank you

**Pull request merged**
